// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// jarvis_march
std::list<std::vector<double> > jarvis_march(std::list<std::vector<double> > list_of_points);
RcppExport SEXP _JarvisMarch_jarvis_march(SEXP list_of_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::list<std::vector<double> > >::type list_of_points(list_of_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(jarvis_march(list_of_points));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_JarvisMarch_jarvis_march", (DL_FUNC) &_JarvisMarch_jarvis_march, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_JarvisMarch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
