# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jarvis_march <- function(list_of_points) {
    .Call(`_JarvisMarch_jarvis_march`, list_of_points)
}

